apt install -y augustus
apt install -y awscli
apt install -y bamtools
apt install -y bandage
apt install -y bbmap
apt install -y bcftools
apt install -y beagle
apt install -y bedops
apt install -y bedtools
apt install -y bioawk
apt install -y biobambam2
apt install -y bowtie2
apt install -y brig
apt install -y busco
apt install -y bwa
apt install -y canu
apt install -y cd-hit
apt install -y centrifuge
apt install -y circos
apt install -y clustalx
apt install -y cnvkit
apt install -y cutadapt
apt install -y cutesv
apt install -y delly
#apt install -y diamond-aligner
#apt install -y emboss
apt install -y fast5
apt install -y fastp
apt install -y fastqc
apt install -y fasttree
apt install -y figtree
apt install -y filtlong
apt install -y flexbar
apt install -y freebayes
apt install -y genometools
apt install -y gffread
apt install -y gmap
apt install -y h5utils
apt install -y hhsuite
apt install -y hisat2
apt install -y hmmer2
apt install -y igv
apt install -y iqtree
apt install -y ivar
apt install -y jellyfish
apt install -y kallisto
apt install -y kmer
apt install -y kraken2
apt install -y last-align
apt install -y lastz
apt install -y mafft
apt install -y malt
apt install -y megahit
apt install -y megan-ce
apt install -y metastudent
apt install -y miniasm
apt install -y minimap2
apt install -y mmseqs2
apt install -y mothur
apt install -y multiqc
apt install -y mummer
apt install -y muscle
apt install -y nanook
apt install -y nanopolish
apt install -y nanostat
apt install -y nanosv
apt install -y ncbi-acc-download
apt install -y ncbi-blast+
apt install -y ncbi-entrez-direct
apt install -y ngmlr
apt install -y parallel
apt install -y pbbamtools
apt install -y pbhoney
apt install -y pbjelly
apt install -y pbsim
apt install -y phylip
apt install -y picard-tools
apt install -y pilon
apt install -y pinfish
apt install -y pirs
apt install -y plink
apt install -y porechop
apt install -y pplacer
apt install -y prodigal
apt install -y prokka
apt install -y qcat

apt install -y quicktree
apt install -y racon
apt install -y ray
apt install -y readseq
apt install -y rna-star
apt install -y rsem
apt install -y salmon
apt install -y sambamba
apt install -y samblaster
apt install -y samtools
apt install -y seqcluster
apt install -y seqkit
apt install -y seqtk
apt install -y shasta
apt install -y sift
apt install -y snakemake
apt install -y sniffles
apt install -y snpeff
apt install -y snpsift
apt install -y soapaligner
apt install -y soapdenovo2
apt install -y soapsnp
apt install -y spades

apt install -y stringtie
apt install -y subread
apt install -y tabix
apt install -y tombo
apt install -y transdecoder
apt install -y treeview
apt install -y trf
apt install -y trimmomatic
apt install -y trinity
apt install -y trinityrnaseq
apt install -y trnascan-se
apt install -y ugene
apt install -y unicycler
apt install -y varscan
apt install -y vcftools
apt install -y vdjtools
apt install -y velvet

apt install -y vg
apt install -y vienna-rna
apt install -y virulencefinder
apt install -y vsearch
apt install -y wtdbg2
apt install -y plink2 plink1.9


